apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
  labels:
    self-managed-add-on: true
    add-on-version: "v0.27.3"
spec:
  releaseName: karpenter
  targetNamespace: karpenter
  storageNamespace: karpenter
  interval: 1m0s
  chart:
    spec:
      chart: karpenter
      version: v0.27.3
      sourceRef:
        kind: HelmRepository
        name: karpenter
  values:
    serviceAccount:
      create: true
      name: karpenter # SA created via eksctl or
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::388900015321:role/karpenter_controller # Replace
    settings:
      aws:
        clusterName: eks-upgrades-workshop
        clusterEndpoint: https://9910482EE6135E61D26FF5ED8A0CC43D.gr7.us-east-1.eks.amazonaws.com # Replace
        defaultInstanceProfile: KarpenterNodeInstanceProfile-eks-upgrades-workshop # Replace
        # interruptionQueueName: eks-upgrade-demo
  install: {}
 